/**
 * Initial state fixtures for pure progression-system tests.
 *
 * The shipped game uses the Village save boundary. This module intentionally
 * contains no Zustand store, persistence, migration, or runtime actions.
 */

import type { MetaState, RunState } from '../types';
import { EMPTY_ASC_TREE } from '../data/ascTree';
import { INITIAL_ACHIEVEMENTS } from '../data/achievementsTypes';
import { EMPTY_COMPASS_OWNED } from '../data/compass';
import { BASE_TRAIT_IDS } from '../data/traits';
import { EMPTY_RELIC_STACKS } from '../data/relics';
import { createInitialPets } from '../systems/petSystem';

export type { MetaState } from '../types';

export const INITIAL_RUN: RunState = {
  characterId: '',
  level: 1,
  exp: 0,
  bp: 30,
  statPoints: 0,
  allocated: { hp: 0, atk: 0, def: 0, agi: 0, luc: 0 },
  currentDungeonId: null,
  currentFloor: 1,
  isHardMode: false,
  monstersDefeated: 0,
  goldThisRun: 0,
  currentStage: 1,
  dungeonRunMonstersDefeated: 0,
  featherUsed: 0,
  playerHp: null,
  currentRealmId: 'base',
  npcs: [],
  heroSnapshot: null,
  directive: null,
};

export const INITIAL_META: MetaState = {
  inventory: { weapons: [], armors: [], accessories: [] },
  baseAbilityLevel: 0,
  soulGrade: 0,
  hardModeUnlocked: false,
  characterLevels: {},
  bestRunLevel: 0,
  normalBossesKilled: [],
  hardBossesKilled: [],
  gold: 0,
  dr: 0,
  enhanceStones: 0,
  equippedItemIds: [],
  equipSlotCount: 1,
  lastPlayedCharId: '',
  questProgress: {},
  questsCompleted: [],
  regionsVisited: [],
  dungeonProgress: {},
  dungeonFinalsCleared: [],
  pendingFinalClearedId: null,
  crackStones: 0,
  ascTier: 0,
  ascPoints: 0,
  ascTree: { ...EMPTY_ASC_TREE },
  tutorialDone: false,
  tutorialStep: -1,
  musicVolume: 0.5,
  sfxVolume: 0.7,
  muted: false,
  jp: {},
  jpEarnedTotal: {},
  jpCap: { hwarang: 50, mudang: 50, choeui: 50 },
  jpFirstKillAwarded: {},
  jpCharLvAwarded: {},
  jpPerksOwned: {},
  skillLevels: {},
  ultSlotPicks: {
    hwarang: [null, null, null, null],
    mudang: [null, null, null, null],
    choeui: [null, null, null, null],
  },
  relicStacks: { ...EMPTY_RELIC_STACKS },
  mythicOwned: [],
  mythicEquipped: [null, null, null, null, null],
  mythicSlotCap: 0,
  adsToday: 0,
  adsLastResetTs: 0,
  adsWatched: 0,
  compassOwned: { ...EMPTY_COMPASS_OWNED },
  dungeonMiniBossesCleared: [],
  dungeonMajorBossesCleared: [],
  adFreeOwned: false,
  lastIapTx: [],
  cycleHistory: [],
  traitsUnlocked: [...BASE_TRAIT_IDS],
  sagaHistory: [],
  sponsorGold: 0,
  atkBaseBonus: 0,
  hpBaseBonus: 0,
  luckBaseBonus: 0,
  light: 0,
  buffLevels: {},
  unlockedRealms: ['base'],
  eternalSaga: { events: [], chaptersByEra: {}, rejuvenationCount: 0, realmTransitions: [] },
  season: { current: 'spring', startedAtAge: 0 },
  hall: { entries: [] },
  achievements: INITIAL_ACHIEVEMENTS,
  tokens: 0,
  tokensRedeemed: 0,
  seasonStartedAt: 0,
  battleSpeed: 1,
  gambitPolicy: 'always',
  bestiary: {},
  ascensionTrialClearedFloor: 0,
  pets: createInitialPets(),
  activePetId: 'white_tiger',
  zodiacUnlocked: [],
  starlightShards: 0,
  elixirDoses: {},
  awakeningTier: 0,
  highestRiftDepth: 0,
  carvedGems: [],
  transmutedRelics: [],
  apexTrialsCleared: [],
  dimensionalEssence: 0,
  corridorSectorsCleared: [],
  primordialRanks: {},
  claimedArchiveMilestones: [],
  totalRebirths: 0,
  chronoEssence: 0,
  activeRebirthTier: null,
  chronoLoomRanks: {},
  pantheonHighestPhase: 0,
  pantheonClears: 0,
  pantheonCrests: 0,
  forgedRegalia: [],
  paradoxHighestFloor: 0,
};
