export const ELITE_GOLD_CASCADE_PER_ELITE = 0.01;
export const ELITE_GOLD_CASCADE_CAP = 1.3;
export const PRESTIGE_ATK_MOMENTUM_RATE = 0.005;
export const PRESTIGE_ATK_MOMENTUM_CAP = 1.3;
export const DANGER_EXP_SURGE_BONUS = 10;
export const COMBO_GOLD_MILESTONE2_INTERVAL = 25;
export const COMBO_GOLD_MILESTONE2_BONUS = 15;
export const BOSS_SHIELD_GRANT_DURATION = 2;
export const WAVE_EXP_MASTERY_RATE = 0.002;
export const WAVE_EXP_MASTERY_CAP = 1.3;
export const ELITE_ATK_CHAIN_BONUS2 = 0.08;
export const ELITE_ATK_CHAIN_CAP2 = 1.3;
export const PRESTIGE_GOLD_BURST_PER_PRESTIGE = 30;
export const DEATH_COMBO_PRESERVE_RATE = 0.3;
export const VILLAGE_DANGER_RESET = true;
export const FINAL_MASTERY_RATE = 0.0005;
export const FINAL_MASTERY2_CAP = 1.2;
export const BLOOD_PACT_HP_COST = 0.1;
export const BLOOD_PACT_ATK_BONUS = 0.25;
export const BLOOD_PACT_THRESHOLD = 0.5;
export const GREED_GAMBIT_GOLD_THRESHOLD = 500;
export const GREED_GAMBIT_EXP_BONUS = 0.2;
export const GREED_GAMBIT_GOLD_PENALTY = 0.15;
export const ADRENALINE_RUSH_HP_THRESHOLD = 0.2;
export const ADRENALINE_RUSH_ATK_BONUS = 0.5;
export const SACRIFICE_GOLD_RATE = 0.03;
export const SACRIFICE_GOLD_EXP_RATIO = 2;
export const RISK_REWARD_DANGER_EXP = 0.05;
export const RISK_REWARD_DANGER_DEATH_PENALTY = 0.02;
export const SHIELD_SACRIFICE_ATK_MUL = 2.0;
export const SHIELD_SACRIFICE_CHANCE = 0.1;
export const COMBO_TAX_THRESHOLD = 15;
export const COMBO_TAX_RATE = 0.02;
export const COMBO_TAX_REWARD_MUL = 0.1;
export const PRESTIGE_ECHO_DURATION = 20;
export const PRESTIGE_ECHO_BONUS = 0.3;
export const PRESTIGE_ECHO_DECAY = 0.015;
export const BOSS_ENRAGE_REWARD_MUL = 3.0;
export const BOSS_ENRAGE_DMG_MUL = 2.0;
export const BOSS_ENRAGE_CHANCE = 0.2;
export const WAVE_EXHAUSTION_ATK_PENALTY = 0.1;
export const WAVE_EXHAUSTION_DURATION = 3;
export const WAVE_EXHAUSTION_GOLD_BONUS = 0.3;
export const LOW_HP_FURY_THRESHOLD = 0.2;
export const LOW_HP_FURY_ATK_MUL = 2.0;
export const FULL_HP_FORTUNE_GOLD_MUL = 1.5;
export const COMBO_GATE_THRESHOLD = 50;
export const COMBO_GATE_EXP_BURST = 500;
export const GOLD_THRESHOLD_DEF_MUL = 100;
export const GOLD_THRESHOLD_DEF_BONUS = 0.15; // C615: 0.5→0.15, was too much free DR
export const DEATH_PROXIMITY_CRIT_DURATION = 1;
export const BOSS_CONDITIONAL_MUL = 1.2;
export const ELITE_HUNTER_STREAK = 3;
export const ELITE_HUNTER_REWARD_MUL = 3.0;
export const DEEP_DANGER_THRESHOLD = 8;
export const DEEP_DANGER_EXP_MUL = 1.5;
export const PRESTIGE_READY_BONUS_PER_FIGHT = 0.02;
export const PRESTIGE_READY_BONUS_CAP = 0.5;
export const CONDITIONAL_STACK_BONUS = 0.05;
export const CONDITIONAL_STACK_CAP = 0.5;
export const GOLD_BURN_RATE = 0.25;
export const GOLD_BURN_ATK_PER_100 = 1;
export const GOLD_BURN_COOLDOWN = 10;
export const LEVEL_SACRIFICE_RATE = 0.18; // C678: was 0.25 (compound cliff too harsh)
export const COMBO_RESET_GOLD_PER_COMBO = 10;
export const EXP_OFFERING_RATE = 0.5;
export const EXP_OFFERING_BOSS_MUL = 3.0;
export const SHIELD_BREAK_BURST_MUL = 3.0;
export const SHIELD_BREAK_BURST_DURATION = 5;
export const DANGER_BET_INCREASE = 3;
export const DANGER_BET_LOCK_MUL = 1.5;
export const DANGER_BET_DURATION = 10;
export const HEALTH_TAX_HP_COST = 0.2;
export const HEALTH_TAX_GOLD_PER_FIGHT = 50;
export const SACRIFICE_ALTAR_COOLDOWN = 15;
export const SACRIFICE_DIMINISH_RATE = 0.9;
export const SACRIFICE_DIMINISH_CAP = 0.5;
export const SACRIFICE_PRESTIGE_RATE = 0.01;
export const SACRIFICE_PRESTIGE_CAP = 0.5;
export const MOMENTUM_DECAY_RATE = 0.05;
export const GOLDEN_HOUR_INTERVAL = 50;
export const GOLDEN_HOUR_DURATION = 10;
export const GOLDEN_HOUR_GOLD_MUL = 2.0;
export const FATIGUE_ONSET = 100;
export const FATIGUE_ATK_PENALTY_PER_FIGHT = 0.005;
export const FATIGUE_CAP = 0.3;
export const ACCUMULATOR_PER_CLEAN = 0.02;
export const ACCUMULATOR_CAP = 1.0;
export const SEASON_LENGTH = 25;
export const RUSH_HOUR_START = 200;
export const RUSH_HOUR_DURATION = 10;
export const RUSH_HOUR_GOLD_MUL = 3.0;
export const RUSH_HOUR_EXP_MUL = 0.5;
export const AGING_INTERVAL = 50;
export const AGING_EXP_BONUS = 0.03;
export const AGING_ATK_PENALTY = 0.02;
export const AGING_CAP = 10;
export const REJUVENATION_AGE = 10;
export const REJUVENATION_EXP_BURST = 1000;
export const TIME_LOCK_GROWTH = 0.5;
export const TIME_LOCK_DURATION = 20;
export const TIME_LOCK_DEPOSIT_RATE = 0.1;
export const TEMPORAL_PRESTIGE_FAST_THRESHOLD = 100;
export const TEMPORAL_PRESTIGE_FAST_BONUS = 0.2;
export const TEMPORAL_PRESTIGE_SLOW_BONUS = 0.1;
export const BLOOD_FURY_SYNERGY_MUL = 1.3; // C573: was 1.5
export const WEALTH_SACRIFICE_EFFICIENCY = 2.0;
export const TEMPORAL_COMBO_DISCOUNT = 0.5;
export const ELDER_WISDOM_AGE = 5;
export const ELDER_WISDOM_PRESTIGE = 3;
export const ELDER_WISDOM_EXP_MUL = 1.5;
export const DESPERATE_TRADE_CRIT_MUL = 3.0;
export const SYNERGY_COUNT_BONUS = 0.05;
export const SYNERGY_COUNT_CAP = 0.3;
export const SYNERGY_TIER_3_BONUS = 0.1;
export const SYNERGY_TIER_5_BONUS = 0.25;
export const ANTI_SYNERGY_PENALTY = 0.5;
export const SYNERGY_PRESTIGE_RATE = 0.02;
export const SYNERGY_PRESTIGE_CAP = 0.3;
export const TOTAL_SYNERGIES = 8;
export const RELIC_DROP_CHANCE_ELITE = 0.10;
export const RELIC_DROP_CHANCE_BOSS = 0.25;
export const RELIC_UPGRADE_CHANCE = 0.15;
export const RELIC_MAX_SLOTS = 3;
export const RELIC_MAX_LEVEL = 5; // C763: cap relic levels to prevent infinite scaling
export const EMBER_CROWN_ATK_PER_CRIT = 0.02;
export const EMBER_CROWN_CAP = 0.35; // C573: was 0.5
export const MISER_POUCH_GOLD_MUL = 1.4;
export const MISER_POUCH_HEAL_PENALTY = 0.5;
export const HOURGLASS_DURATION_MUL = 1.5; // C573: was 2
export const BLOOD_PACT_RELIC_EFFICIENCY = 1.6; // C573: was 2.0
export const BLOOD_PACT_RELIC_HP_PENALTY = 1.5; // C573: was 0.3 (buff) → now penalty (cost +50%)
export const SCHOLAR_LENS_EXP_MUL = 1.5;
export const SCHOLAR_LENS_ATK_PENALTY = 0.2;
export const RELIC_UPGRADE_BONUS = 0.5;
export const RELIC_PRESTIGE_RETENTION = 0.2; // C573: was 0.3
export const MERCHANT_EVENT_CHANCE = 0.03;
export const MERCHANT_PRICE_MUL = 3;
export const TREASURE_SHRINE_CHANCE = 0.08; // C607: was 0.02 (critic: decision freq too low)
export const SHRINE_GOLD_BURST = 500;
export const SHRINE_EXP_BURST = 300;
export const SHRINE_HEAL_AMOUNT = 0.3; // C582: was 0.5, nerf to make gold/exp competitive
export const TRAP_CHANCE = 0.04;
export const TRAP_DAMAGE = 0.15; // C696: was 0.20, less punishing
export const TRAP_GOLD_LOSS = 100;
export const TRAP_AVOID_COMBO = 20;
export const REST_SHRINE_CHANCE = 0.02;
export const GAMBLER_CHANCE = 0.03; // C696: was 0.015, more frequent
export const GAMBLER_WIN_RATE = 0.40; // C714: was 0.45, high-risk identity
export const GAMBLER_BET_HIGH_REWARD_MUL = 3; // C714: was 2 (implicit), 3x gold on win
export const GAMBLER_BET_HIGH_LOSS_RATE = 0.60; // C714: was 0.80, recovery time reduction
export const GAMBLER_BET_LOW_LOSS_RATE = 0.25;
export const EVENT_PITY_THRESHOLD = 18; // C743: was 20, slightly more frequent events
export const HEALER_EVENT_CHANCE = 0.03; // C743: mid-game healer
export const HEALER_HEAL_RATE = 0.25; // heals 25% of max HP
export const HEALER_MIN_FIGHTS = 30; // only triggers after 30 fights
export const ECHO_EVENT_CHANCE = 0.02; // C743: prestige echo event
export const ECHO_DURATION = 10; // shorter than full prestige echo (20)
export const ECHO_MIN_LEVEL = 5; // only for mid-game heroes
export const INSPIRATION_EVENT_CHANCE = 0.025; // C747: ATK buff event
export const INSPIRATION_ATK_BONUS = 0.15; // +15% ATK for duration
// C753: INSPIRATION_DURATION and INSPIRATION_MIN_FIGHTS removed — replaced by getInspirationConfig() in ConstantPhaseProfile.ts
export const BLACKSMITH_CHANCE = 0.02;
export const BLACKSMITH_BOOST = 5;
export const CURSED_ALTAR_CHANCE = 0.025; // C696: was 0.015, more frequent
export const CURSED_ALTAR_ATK_BUFF = 1.8; // C704: was 1.5, burst value up for boss threshold
export const CURSED_ALTAR_DAMAGE_MUL = 1.5; // C704: was 2.0, sacrifice EV now marginal-positive
export const CURSED_ALTAR_DURATION = 20; // C709: was 30, early-snowball prevention
export const CURSED_ALTAR_HP_THRESHOLD = 0.40; // C702: sacrifice blocked if HP ratio below this
export const FAIRY_CHANCE = 0.02;
export const FAIRY_DURATION = 5;
export const TIME_RIFT_CHANCE = 0.01;
export const EVENT_CHAIN_THRESHOLD = 3;
export const EVENT_CHAIN_REWARD_EXP = 1000;
export const EVENT_CHAIN_REWARD_GOLD = 2000;
export const VILLAGE_GOLD_FOUNTAIN = 25;
export const DANGER_TAX_IMMUNITY = true;
export const CRIT_STREAK_GUARANTEE_THRESHOLD = 3;
export const BOSS_KILL_EXP_MUL = 3.0;
export const GOLD_INVEST_LOCK_FIGHTS = 10;
export const GOLD_INVEST_RETURN_MUL = 3;
export const GOLD_INVEST_MIN = 100;
export const DAMAGE_REFLECT_RATE = 0.05;
export const PASSIVE_GOLD_PER_VISIT = 1;
export const PASSIVE_GOLD_CAP = 10;
export const BOSS_IMMUNITY_INTERVAL = 3;
export const ACHIEVEMENT_KILL_THRESHOLDS = [100, 500, 1000];
export const ACHIEVEMENT_ATK_BONUS = 0.05;
export const WEATHER_CHANCE = 0.20; // C781: tuned from 0.30 (uptime 70%→53%, weather stays "special")
// C777: weather duration — once weather occurs it persists for multiple fights
export const WEATHER_DURATION_MIN = 3;
export const WEATHER_DURATION_MAX = 8;
export const WEATHER_RAIN_ATK_PENALTY = 0.1;
export const WEATHER_WIND_EXP_BONUS = 0.2;
export const WEATHER_FOG_CRIT_PENALTY = 0.80; // C781: tuned from 0.70 (crit-build nerf -30%→-20%)
export const ARENA_COST = 200;
export const ARENA_REWARD_MUL = 5;
export const ARENA_ENEMY_HP_MUL = 3;
export const SHRINE_SKILL_GRANT_RATE = 0.20;
export const MERCIFUL_PROC_RATE = 0.04;
// C757: Ancient Colosseum constants
export const COLOSSEUM_EXP_MUL = 2.0;
export const COLOSSEUM_ENEMY_ATK_MUL = 1.7; // C790: tuned from 1.5 (bracket separation from Abyssal 1.60)
// C762: Trial Grounds constants
export const TRIAL_GROUNDS_EXP_MUL = 1.40; // C779: tuned from 1.50 (R:R 2.80→2.25, meaningful decision)
export const TRIAL_GROUNDS_LEVEL_MUL = 1.20; // C774: tuned from 1.10 (R:R 1:5→1:2.5, meaningful decision)
export const TRIAL_GROUNDS_DURATION = 3;

export const STORM_NEXUS_ATK_MUL = 1.40; // C770: Storm Nexus ATK buff
export const STORM_NEXUS_HP_DRAIN_RATE = 0.05; // C770: 5% HP drain per fight
export const STORM_NEXUS_DURATION = 4; // C770: 4 fights

export const VOID_RIFT_SCALE_PER_TIER = 0.05; // C771: 5% per tier (lv200: +5%, lv800: +15%)
export const VOID_RIFT_EXP_PER_TIER = 0.09; // C781: tuned from 0.06 (R:R 1.20→1.80, meaningful accept)

// C773: Rain Sanctuary — heal + gold penalty tradeoff (rain-only)
export const RAIN_SANCTUARY_HEAL_RATE = 0.20; // 20% hpMax instant heal
export const RAIN_SANCTUARY_GOLD_MUL = 0.70; // gold ×0.7 during duration
export const RAIN_SANCTUARY_DURATION = 3; // 3 fights

// C773: Fog Ambush — consecutive fights with ATK penalty, EXP reward (fog-only)
export const FOG_AMBUSH_ENEMY_ATK_MUL = 1.20; // enemies hit 20% harder
export const FOG_AMBUSH_EXP_MUL = 1.30; // +30% EXP reward
export const FOG_AMBUSH_DURATION = 2; // 2 consecutive fights

// C782→C785: Wind Gale — EXP boost + dodge bonus, gold penalty (wind-only)
export const WIND_GALE_EXP_MUL = 1.15; // C790: tuned from 1.20 (low-risk event)
export const WIND_GALE_DODGE_BONUS = 0.10; // +10% dodge chance (was 0.15)
export const WIND_GALE_GOLD_PENALTY = 0.60; // gold income ×0.60 during gale
export const WIND_GALE_DURATION = 3; // 3 fights

// C782→C785: Snow Drift — defensive event: enemy damage reduction + hero ATK penalty (snow-only)
export const SNOW_DRIFT_ENEMY_SPD_MUL = 0.80; // enemy speed -20% (was 0.70)
export const SNOW_DRIFT_DMG_MUL = 0.85; // actual damage reduction (SPD≠DMG)
export const SNOW_DRIFT_ATK_PENALTY = 0.80; // C790: hero ATK ×0.80 (was 0.92, R:R was auto-accept)
export const SNOW_DRIFT_DURATION = 4; // C790: 4 fights (was 3, defensive events need longer)
export const SNOW_DRIFT_EXP_MUL = 1.10; // C790: +10% EXP reward for meaningful choice

// C775: Event decline consolation
export const EVENT_DECLINE_GOLD_RATE = 0.02; // gold × 0.02 × comboStreak
export const EVENT_DECLINE_GOLD_CAP = 50; // max 50 gold consolation

// C789: Late-game density scaling
export const LATE_GAME_DENSITY_THRESHOLD = 200; // fights after which event chance increases
export const LATE_GAME_DENSITY_MUL = 1.5; // ×1.5 event chance after threshold

// C789: Abyssal Convergence event (late-game, fight 250+)
export const ABYSSAL_CONVERGENCE_DURATION = 5; // 5 fights
export const ABYSSAL_CONVERGENCE_EXP_MUL = 1.50; // EXP ×1.50
export const ABYSSAL_CONVERGENCE_ENEMY_ATK_MUL = 1.60; // enemy ATK ×1.60
export const ABYSSAL_CONVERGENCE_HP_DRAIN_RATE = 0.03; // 3% HP drain per fight

// C791: Temporal Fissure — delayed EXP gratification
export const TEMPORAL_FISSURE_DURATION = 5; // store EXP for 5 fights
export const TEMPORAL_FISSURE_STORE_RATE = 0.50; // store 50% of earned EXP
export const TEMPORAL_FISSURE_PAYBACK_MUL = 2.0; // pay back stored ×2.0 at end

