export const DANGER_ZONE_RATE = 0.15;
export const DANGER_ZONE_STAT_MUL = 2.5; // C605: was 1.5
export const DANGER_ZONE_EXP_MUL = 4; // C598: was 3
export const COMBO_STREAK_THRESHOLD = 3;
export const COMBO_STREAK_EXP_BONUS = 0.1;
export const MILESTONE_LEVELS = [10, 50, 100, 500, 1000, 5000, 10000, 50000, 100000];
export const CRIT_STREAK_THRESHOLD = 5;
export const CRIT_CHANCE = 0.20;
export const CRIT_DAMAGE_MUL = 1.5; // C629: was 2. Reduced crit spike
export const OVERKILL_DROP_BONUS = 0.15;
export const CLOSE_CALL_THRESHOLD = 0.10;
export const CLOSE_CALL_HEAL = 0.05;
export const MOMENTUM_ATK_BONUS = 0.02;
export const MOMENTUM_CAP = 10; // C625: was 20. Reduced ATK snowball ceiling
export const DROP_STREAK_THRESHOLD = 3;
export const BOSS_RAGE_ATK_PER_TURN = 0.10;
export const ELITE_SPAWN_RATE = 0.05;
export const ELITE_HP_MUL = 2.0;
export const ELITE_EXP_MUL = 2.5;
export const VILLAGE_REST_HP_THRESHOLD = 0.30;
export const VILLAGE_REST_HP_BOOST = 0.01;
export const SHRINE_MEDITATION_ATK_BUFF = 0.15; // C645: was 0.25. Shrine buff less impactful
export const SHRINE_MEDITATION_BUFF_DURATION = 5;
export const DEATH_STREAK_THRESHOLD = 3;
export const MERCY_DAMAGE_REDUCTION = 0.15; // C611: was 0.30
export const MERCY_DURATION = 2; // C611: was 3
export const EXP_DIMINISH_THRESHOLD = 1000;
export const EXP_DIMINISH_FACTOR = 0.0005;
export const FIRST_BLOOD_EXP_MUL = 2.0;
export const FIRST_BLOOD_DROP_GUARANTEE = true;
export const REVENGE_ATK_BONUS = 0.25; // C641: was 0.50. Revenge bonus too generous
export const SURVIVAL_STREAK_THRESHOLD = 10;
export const SURVIVAL_STREAK_EXP_BONUS = 0.05;
export const LUCKY_DODGE_CHANCE = 0.05; // C582: was 0.10
export const GOLD_PER_KILL_BASE = 5;
export const GOLD_BOSS_MUL = 5;
export const GOLD_ELITE_MUL = 3;
export const WAVE_INTERVAL = 20;
export const WAVE_SIZE = 3;
export const WAVE_BONUS_EXP_MUL = 2.0;
export const WAVE_BONUS_GOLD_MUL = 3.0;
export const GOLD_DEATH_PENALTY = 0.10;
export const KILL_MILESTONE_INTERVAL = 50;
export const KILL_MILESTONE_ATK_BONUS = 0.01;
export const GOLD_MOMENTUM_THRESHOLD = 5;
export const GOLD_MOMENTUM_BONUS = 0.50;
export const AREA_FAMILIARITY_EXP_BONUS = 0.05;
export const AREA_FAMILIARITY_CAP = 5;
export const TREASURE_GOBLIN_RATE = 0.03;
export const TREASURE_GOBLIN_GOLD_MUL = 10;
export const TREASURE_GOBLIN_HP_MUL = 0.3;
export const TREASURE_GOBLIN_FLEE_RATE = 0.4;
export const COMBO_GOLD_THRESHOLD = 3;
export const COMBO_GOLD_BONUS_PER = 0.20;
export const VILLAGE_SHOP_COST = 50;
export const VILLAGE_SHOP_SHIELD_MUL = 0.20;
export const VILLAGE_SHOP_SHIELD_DURATION = 3;
export const OVERKILL_GOLD_BONUS = 1.0;
export const WIN_HP_REGEN_RATE = 0.015; // C715: was 0.01, early-game survival buff
export const BOSS_VAULT_GOLD_PER_LEVEL = 100;
export const NEAR_DEATH_HP_THRESHOLD = 0.10;
export const NEAR_DEATH_ATK_MUL = 1.25; // C636: was 1.5. Reduce low-HP ATK spike
export const GOLD_SAVE_CHANCE = 0.25;
export const COMBO_EXP_THRESHOLD = 10;
export const COMBO_EXP_BONUS_PER = 0.10;
export const CRIT_GOLD_BONUS = 0.30;
export const DANGER_ZONE_GOLD_MUL = 3.0; // C598: was 2.0
export const GOLD_LEVEL_POWER = 1.2;
export const BOSS_ENRAGE_HP_THRESHOLD = 0.5;
export const BOSS_ENRAGE_ATK_MUL = 2.0;
export const EXP_OVERFLOW_GOLD_RATIO = 100;
export const CLOSE_CALL_HP_THRESHOLD = 0.20;
export const CLOSE_CALL_EXP_BONUS = 0.50;
export const VILLAGE_GOLD_INTEREST_RATE = 0.02;
export const WAVE_MULTI_KILL_ATK_BONUS = 1;
export const GREED_MODE_GOLD_THRESHOLD = 1000;
export const GREED_MODE_EXP_PENALTY = 0.20;
export const GREED_MODE_GOLD_BONUS = 1.0;
export const DODGE_PER_100_KILLS = 0.05;
export const DODGE_CAP = 0.20;
export const BOSS_STREAK_MULTIPLIER = 1;
export const EXHAUSTION_THRESHOLD = 50;
export const EXHAUSTION_ATK_PENALTY = 0.10;
export const LIFESTEAL_RATE = 0.01;
export const SHRINE_TITHE_RATE = 0.10;
export const SHRINE_TITHE_ATK_BONUS = 0.02;
export const LUCKY_TREASURE_CHANCE = 0.05;
export const LUCKY_TREASURE_MIN = 50;
export const LUCKY_TREASURE_MAX = 200;
export const DANGER_STREAK_EXP_STEP = 0.5;
export const DANGER_STREAK_EXP_CAP = 3.0;
export const SHIELD_BREAK_ATK_MUL = 1.5;
export const GOLD_MAGNET_COMBO_THRESHOLD = 7;
export const GOLD_MAGNET_GOBLIN_MUL = 2.0;
export const DEATH_HP_DECAY_RATE = 0.01;
export const VILLAGE_HEAL_BASE = 0.25;
export const VILLAGE_HEAL_PER_VISIT = 0.01;
export const VILLAGE_HEAL_CAP = 0.40;
export const OVERKILL_STREAK_THRESHOLD = 3;
export const OVERKILL_INVINCIBILITY_FIGHTS = 0; // C582: removed
export const LEVEL_UP_EXP_BONUS = 1.0;
export const ELITE_BOUNTY_INTERVAL = 5;
export const ELITE_BOUNTY_EXP_BONUS = 0.05;
export const BOSS_OVERKILL_VAULT_MUL = 2.0;
export const CAVE_TREASURE_CHANCE = 0.30;
export const CAVE_TREASURE_MIN = 100;
export const CAVE_TREASURE_MAX = 500;
export const REVENGE_GOLD_FIGHTS = 3;
export const REVENGE_GOLD_BONUS = 0.50;
export const SHRINE_MASTERY_THRESHOLD = 5;
export const SHRINE_MASTERY_MEDITATION_CHANCE = 0.40;
export const GOLD_ARMOR_THRESHOLD = 2000; // C613: was 500
export const GOLD_ARMOR_REDUCTION = 0.05; // C613: was 0.10
export const BOSS_RAGE_RESET_ON_CRIT = true;
export const GOLD_TAX_LEVEL_THRESHOLD = 50;
export const GOLD_TAX_RATE = 0.05;
export const DOUBLE_HIT_KILL_THRESHOLD = 200;
export const DOUBLE_HIT_CHANCE = 0.10;
export const GOLD_HEAL_HP_THRESHOLD = 0.10; // C605: was 0.20
export const GOLD_HEAL_COST = 100;
export const GOLD_HEAL_AMOUNT = 0.15; // C605: was 0.30
export const EXP_DECAY_LEVEL_START = 100;
export const EXP_DECAY_PER_LEVEL = 0.005;
export const EXP_DECAY_CAP = 0.35;
export const SURVIVOR_THRESHOLD = 100;
export const SURVIVOR_HP_BONUS = 0.10;
export const COMBO_BREAKER_ATK_BONUS = 0.30;
export const BOSS_STREAK_STAT_SCALE = 0.05;
export const PRESTIGE_LEVEL_REQUIREMENT = 200;
export const PRESTIGE_STAT_BONUS = 0.10;
export const PRESTIGE_LEVEL_INCREMENT = 50;
export const TREASURE_HUNTER_CAVE_INTERVAL = 5;
export const TREASURE_HUNTER_GOLD_BONUS = 0.10;
export const EXP_SHIELD_PRESERVE = 0.5;
export const ELITE_COMBO_THRESHOLD = 3;
export const ELITE_COMBO_DROP_GUARANTEE = true;
export const REGEN_SCALE_PER_50_KILLS = 0.001;
export const REGEN_SCALE_CAP = 0.03; // C715: was 0.05, late-game immortality prevention
export const GOLD_STREAK_THRESHOLD = 5;
export const GOLD_STREAK_BONUS = 0.5;
export const DEATH_ATK_BONUS = 0.01;
export const DEATH_ATK_CAP = 0.20;
export const NIGHT_CYCLE_INTERVAL = 20;
export const NIGHT_DURATION = 5;
export const NIGHT_EXP_MUL = 2.0;
export const NIGHT_ENEMY_DMG_MUL = 1.5;
export const LUCKY_FIND_CHANCE = 0.02;
export const EXP_CHAIN_KILLS_THRESHOLD = 5;
export const EXP_CHAIN_BONUS = 0.25;
export const BERSERKER_HP_THRESHOLD = 0.25;
export const BERSERKER_ATK_BONUS = 0.20; // C642: was 0.40. Reduced low-HP power spike
export const BERSERKER_CRIT_BONUS = 0.20;
export const GOLD_INTEREST_PRESTIGE_BONUS = 0.01;
export const DANGER_MAGNET_THRESHOLD = 10;
export const DANGER_MAGNET_SPAWN_BONUS = 0.10;
export const QUICK_KILL_MAX_HITS = 2;
export const QUICK_KILL_EXP_BONUS = 0.10;
export const BOUNTY_KILL_INTERVAL = 25;
export const BOUNTY_GOLD_REWARD = 100;
export const BOSS_ENRAGE_TIMER_TURN = 10;
export const BOSS_ENRAGE_TIMER_MUL = 2.0;
export const COMBO_GOLD_MUL_THRESHOLD = 10;
export const COMBO_GOLD_MUL_BONUS = 0.30;
export const BANK_DEPOSIT_RATE = 0.30;
export const FIRST_HIT_DAMAGE_MUL = 1.2; // C621: was 1.5. Reduced free alpha strike bonus
export const LEVEL_UP_HEAL_RATE = 0.30; // C582: was 0.50
export const CRIT_GOLD_SCALE_PER_100 = 0.10;
export const CRIT_GOLD_SCALE_CAP = 0.50;
export const OVERKILL_HEAL_RATE = 0.02; // C593: was 0.05
export const EXP_OVERFLOW_BONUS = 0.50;
export const DARKNESS_CURSE_DEATHS = 3;
export const DARKNESS_CURSE_ATK_PENALTY = 0.20;
export const BOSS_LOOT_GOLD_MUL = 2.0;
export const BOSS_LOOT_INTERVAL = 5;
export const TIME_PRESSURE_PER_100 = 0.10;
export const TIME_PRESSURE_CAP = 1.00;
export const COMPANION_UNLOCK_WINS = 50;
export const COMPANION_EXP_BONUS = 0.15;
export const ARMOR_BUY_COST = 300;
export const ARMOR_REDUCTION = 0.10;
export const ARMOR_DURATION = 10;
export const SPEC_ATK_BONUS = 0.15; // C648: was 0.25
